%STARTUP
% CHOOSE TO ADD TO THE PATH
%% add MATPOWER paths
addpath( ...
    'C:\Users\mhopkins\Downloads\matpower7.1\matpower7.1\lib', ...
    'C:\Users\mhopkins\Downloads\matpower7.1\matpower7.1\lib\t', ...
    'C:\Users\mhopkins\Downloads\matpower7.1\matpower7.1\data', ...
    'C:\Users\mhopkins\Downloads\matpower7.1\matpower7.1\most\lib', ...
    'C:\Users\mhopkins\Downloads\matpower7.1\matpower7.1\most\lib\t', ...
    'C:\Users\mhopkins\Downloads\matpower7.1\matpower7.1\mp-opt-model\lib', ...
    'C:\Users\mhopkins\Downloads\matpower7.1\matpower7.1\mp-opt-model\lib\t', ...
    'C:\Users\mhopkins\Downloads\matpower7.1\matpower7.1\mips\lib', ...
    'C:\Users\mhopkins\Downloads\matpower7.1\matpower7.1\mips\lib\t', ...
    'C:\Users\mhopkins\Downloads\matpower7.1\matpower7.1\mptest\lib', ...
    'C:\Users\mhopkins\Downloads\matpower7.1\matpower7.1\mptest\lib\t', ...
    'C:\Users\mhopkins\Downloads\matpower7.1\matpower7.1\extras\maxloadlim', ...
    'C:\Users\mhopkins\Downloads\matpower7.1\matpower7.1\extras\maxloadlim\tests', ...
    'C:\Users\mhopkins\Downloads\matpower7.1\matpower7.1\extras\maxloadlim\examples', ...
    'C:\Users\mhopkins\Downloads\matpower7.1\matpower7.1\extras\misc', ...
    'C:\Users\mhopkins\Downloads\matpower7.1\matpower7.1\extras\reduction', ...
    'C:\Users\mhopkins\Downloads\matpower7.1\matpower7.1\extras\sdp_pf', ...
    'C:\Users\mhopkins\Downloads\matpower7.1\matpower7.1\extras\se', ...
    'C:\Users\mhopkins\Downloads\matpower7.1\matpower7.1\extras\smartmarket', ...
    'C:\Users\mhopkins\Downloads\matpower7.1\matpower7.1\extras\state_estimator', ...
    'C:\Users\mhopkins\Downloads\matpower7.1\matpower7.1\extras\syngrid\lib', ...
    'C:\Users\mhopkins\Downloads\matpower7.1\matpower7.1\extras\syngrid\lib\t', ...
    '-end' );
